---
title: "portfolio"
description: |
  A collection of my course projects and personal work. 
output: 
  distill::distill_article:
    css: theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(htmltools)
source("R/functions.R")
```

# course projects
```{r}
create_proj_card(
  img_src = "images/hockey.JPG",
  url = "https://kmiedema.shinyapps.io/project10-steel/",
  title = "Analysis of Top 50 Players in 2020-2021 NHL Season",
  text = "Dashboard created by myself and a partner. 
  I was tasked with creating the shell of the dashboard along with the 
  research questions tabs and conclusion tabs.",
  text2 = ""
)

create_proj_card(
  img_src = "images/vs-1-copy.png",
  url = "https://github.com/miedemakr/Scraping-PACS",
  title = "Web Scraping PAC Data using R",
  text = "Scraped data from OpenSecrets. Then created a function 
  to iterate over multiple URL's. Lastly, analyzed the data using 
  tables and plots created using the ggplot2 package in R.",
  text2 = ""
)
```
